/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 22-sept.-2019 6:40:02 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS usuarios CASCADE
;

/* Create Tables */

CREATE TABLE usuarios
(
	nombre varchar(255) NOT NULL,
	numero_identificacion varchar(50) NOT NULL,
	correo varchar(255) NOT NULL,
	apodo varchar(20) NOT NULL,
	celular varchar(50) NOT NULL,
	direccion varchar(255) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE usuarios ADD CONSTRAINT PK_Usuario
	PRIMARY KEY (apodo)
;
